apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress: "true"
  labels:
    app: test
  name: test
  namespace: devops
spec:
  ports:
  - name: web
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: test
  type: ClusterIP
